FROM node:latest
MAINTAINER Adam Veldhousen @adamveld12

WORKDIR /usr/src/app

RUN npm install webpack webpack-dev-server surge -g

VOLUME ["/usr/src/app"]

EXPOSE 80

ENTRYPOINT npm install && npm run docker-dev